app = "github-analytics"
primary_region = "iad"

[mounts]
  source = "github_analytics_data"
  destination = "/data"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
